### ISSUE TITLE
Problem when trying to updateAction

### ISSUE THREAD

**Issue by semiaLi** [stephpy/timeline#41]
Hello, i have a problem in submitting my action. In fact, i have this error : 
<p>
FatalErrorException: Error: Call to a member function setContext() on a non-object in C:\wamp\www\Rse\vendor\stephpy\timeline-bundle\Driver\Doctrine\AbstractTimelineManager.php line 51
</p>
we can read this 
$timeline
            ->setType($type)
            ->setAction($action)
            ->setContext($context)
            ->setSubject($subject)
        ;
if I change the setting order example like this :
$timeline
            ->setContext($context)
            ->setSubject($subject)
            ->setType($type)
            ->setAction($action)
        ;
it work !! But us you know we can't change the method of imported vender.

Please i need your help.

**Comment by stephpy** [comment]
Hi,

[setAction](https://github.com/stephpy/timeline/blob/master/src/Model/Timeline.php#L142) method return `$this`. It seems you overrided this method and forgot to return $this. No ?

**Comment by semiaLi** [comment]
Thank you , it works :+1:
