### ISSUE TITLE
DuplicateKey filter removes "every second entry" instead of "all but last"

### ISSUE THREAD

**Issue by venimus** [stephpy/timeline#44]
DuplicateKey filter removes "every second entry" instead of "all but last"

To reproduce:
Make 4 timeline entries with the same DuplicateKey and the same priority. Run the filter and it will leave entries 2 and 4.

IMHO bug is caused because of
https://github.com/stephpy/timeline/blob/master/src/Filter/DuplicateKey.php#L42

```
unset($collection[$keyToDelete]);
```

Here it unsets an item of the foreach collection. PHP does not clone it automatically (as it is probably assumed) and removing the entry skips the next iteration.

I would propose replacing https://github.com/stephpy/timeline/blob/master/src/Filter/DuplicateKey.php#L21

with

```
        foreach ($collection as $key => $value) {
            $cloned[$key] = $value;
        }

        foreach ($cloned as $key => $action) {

**Comment by stephpy** [comment]
Hi,

Good catch, could you make a PR please ?
