### ISSUE TITLE
Re-Spread actions ?

### ISSUE THREAD

**Issue by sadortun** [stephpy/timeline#47]
Hi Stéphane,

I have another good implementation question for you! I guess that other users might have that kind of needs. Based on your input i'll re-publish my solution later.

We have geolocated `users` that visit `regions` that are currently in our databases. Once in a while, we add new `regions`. Everything work perfectly with spreads. 

Once in a while (actually, quite often), we add new regions, or we increase the size. We then need to go through the list of actions for users that were inside the new region and re-spread it's action to the new region.

So we need 
1) For each pre-defined actions
2) Re-run the Spreads
3) Check if the action is already present into that specific timeline
4) If not, add it, otherwise, skip it.

Of course other timelines must remain unaffected, and duplicates avoided !

Do you have an idea how we can implement this in an elegant way ?

**Comment by stephpy** [comment]
Hi,

I see what do you expect but it's not the initial goal of this bundle.
Here the bundle works like twitter for example. While you don't follow somebody, you have not its tweets, when you follow him, you'll have its tweets, but not the tweets before you followed him.

For sure, you could have a specific job which re-create timeline entries from old actions.
In your example, you could at each region creation launch a job which look at old actions which have to be relate to this new region, then create specific timeline entries manually.

I guess it should be specific to your application.
It would be hard and opposed to current philosophy of this bundle to implement this kind of feature.

Regards,
